# 05 · Corrections + mini-projet final  ⏱️ ~15 min

⚠️ Essaie **d'abord** les exercices dans chaque notebook avant de regarder ici. Il y a souvent plusieurs bonnes réponses.

In [ ]:
import numpy as np
import pandas as pd

## Corrections — 01 Bases

In [ ]:
# 1. Moyenne
temperatures = [12, 18, 25, 9, 30, 15]
print(sum(temperatures) / len(temperatures))

# 2. Compréhension
print([t for t in temperatures if t > 15])

# 3. Ruptures de stock
stock = {"pommes": 10, "poires": 0, "kiwis": 4}
for fruit, qte in stock.items():
    if qte == 0:
        print("Rupture :", fruit)

# 4. FizzBuzz
for n in range(1, 16):
    if n % 3 == 0 and n % 5 == 0:
        print("FizzBuzz")
    elif n % 3 == 0:
        print("Fizz")
    elif n % 5 == 0:
        print("Buzz")
    else:
        print(n)

18.166666666666668
[18, 25, 30]
Rupture : poires
1
2
Fizz
4
Buzz
Fizz
7
8
Fizz
Buzz
11
Fizz
13
14
FizzBuzz

## Corrections — 02 Fonctions

In [ ]:
def est_pair(n):
    return n % 2 == 0

def moyenne(liste):
    if len(liste) == 0:      # ou : if not liste:
        return None
    return sum(liste) / len(liste)

def convertir_temp(valeur, vers="F"):
    if vers == "F":
        return valeur * 9 / 5 + 32
    return (valeur - 32) * 5 / 9

print(est_pair(4), est_pair(7))
print(moyenne([]), moyenne([10, 20]))
print(convertir_temp(100), convertir_temp(212, vers="C"))
print(sorted(["banane", "kiwi", "ananas", "fraise"], key=lambda m: len(m)))   # ou key=len

True False
None 15.0
212.0 100.0
['kiwi', 'banane', 'ananas', 'fraise']

## Corrections — 03 NumPy

In [ ]:
# 1.
a = np.arange(1, 21)
print(a[a % 3 == 0])

# 2.
rng = np.random.default_rng(seed=0)
tailles = rng.normal(175, 7, size=1000)
print(f"{(tailles > 185).mean():.1%} dépassent 185 cm")   # moyenne d'un masque = proportion de True

# 3.
m = np.arange(20).reshape(4, 5)
print(m[:, 2])
print(m[-1])
print(m.mean(axis=1))

# 4.
v = np.array([5, -2, 8, -7, 3])
v[v < 0] = 0                 # ou : np.where(v < 0, 0, v)  /  np.clip(v, 0, None)
print(v)

[ 3  6  9 12 15 18]
5.8% dépassent 185 cm
[ 2  7 12 17]
[15 16 17 18 19]
[ 2.  7. 12. 17.]
[5 0 8 0 3]

## Corrections — 04 Pandas

In [ ]:
df = pd.read_csv("data/ventes.csv", parse_dates=["date"])
df["quantite"] = df["quantite"].fillna(0)
df["ca"] = df["quantite"] * df["prix_unitaire"]

# 1.
print("Ventes de casques :", (df["produit"] == "Casque").sum())

# 2.
print("CA Sud :", df.loc[df["region"] == "Sud", "ca"].sum())

# 3.
ca_produit = df.groupby("produit")["ca"].sum()
print("Produit n°1 :", ca_produit.idxmax(), "-", ca_produit.max(), "€")

Ventes de casques : 6
CA Sud : 4495.0
Produit n°1 : Écran - 10260.0 €

In [ ]:
# 4.
df.loc[df["vendeur"] == "Chloé", ["date", "produit", "ca"]].sort_values("date")

         date  produit      ca
4  2025-01-18  Clavier     0.0
5  2025-01-26   Souris    30.0
6  2025-01-28  Clavier   150.0
11 2025-02-10   Casque   420.0
16 2025-02-27    Écran  1260.0
22 2025-03-19   Casque   540.0
24 2025-03-22   Casque   180.0
25 2025-03-23  Clavier    50.0
28 2025-04-02   Souris   150.0

In [ ]:
# 5.
df["remise"] = np.where(df["ca"] > 1000, df["ca"] * 0.10, 0)
df[df["remise"] > 0]

         date vendeur region produit  quantite  prix_unitaire      ca  remise
0  2025-01-09   David    Est   Écran       9.0          180.0  1620.0   162.0
9  2025-02-05   David    Est   Écran      11.0          180.0  1980.0   198.0
13 2025-02-14    Emma    Sud   Écran       6.0          180.0  1080.0   108.0
16 2025-02-27   Chloé   Nord   Écran       7.0          180.0  1260.0   126.0
21 2025-03-08    Emma    Sud   Écran      10.0          180.0  1800.0   180.0
27 2025-03-31   Alice   Nord   Écran      10.0          180.0  1800.0   180.0

In [ ]:
# 6.
df.groupby(df["date"].dt.month)["ca"].mean().round(2)

date
1    320.62
2    601.11
3    493.18
4    112.50
Name: ca, dtype: float64

## 🏁 Mini-projet : analyse de notes d'étudiants
Tout ce que tu as vu, dans un seul exercice. Essaie de le faire **sans regarder** la solution en dessous.

1. Génère avec numpy (`seed=1`) un DataFrame de 50 étudiants : colonnes `etudiant` (`"E01"`…`"E50"`),
   `classe` (au hasard parmi `"A"`, `"B"`, `"C"`), `maths`, `physique`, `anglais` (entiers entre 0 et 20).
2. Ajoute une colonne `moyenne` (moyenne des 3 matières, arrondie à 1 décimale).
3. Ajoute une colonne `mention` via une **fonction** + `apply` (≥16 TB, ≥14 B, ≥12 AB, ≥10 Passable, sinon Recalé).
4. Combien d'étudiants par mention ?
5. Moyenne de chaque matière par classe.
6. Le top 5 des étudiants.
7. Les étudiants qui ont au moins 15 en maths **et** moins de 10 en anglais.

In [ ]:
# --- SOLUTION ---
rng = np.random.default_rng(seed=1)
n = 50

notes = pd.DataFrame({
    "etudiant": [f"E{i:02d}" for i in range(1, n + 1)],
    "classe": rng.choice(["A", "B", "C"], size=n),
    "maths": rng.integers(0, 21, size=n),
    "physique": rng.integers(0, 21, size=n),
    "anglais": rng.integers(0, 21, size=n),
})

matieres = ["maths", "physique", "anglais"]
notes["moyenne"] = notes[matieres].mean(axis=1).round(1)   # axis=1 : moyenne sur chaque ligne

def mention(moy):
    if moy >= 16:
        return "TB"
    elif moy >= 14:
        return "B"
    elif moy >= 12:
        return "AB"
    elif moy >= 10:
        return "Passable"
    return "Recalé"

notes["mention"] = notes["moyenne"].apply(mention)
notes.head()

  etudiant classe  maths  physique  anglais  moyenne   mention
0      E01      B      1         1       18      6.7    Recalé
1      E02      B     15        14        0      9.7    Recalé
2      E03      C      6        15       10     10.3  Passable
3      E04      C     11        16       14     13.7        AB
4      E05      A     19        18        9     15.3         B

In [ ]:
notes["mention"].value_counts()

mention
Recalé      22
B           10
Passable     9
AB           9
Name: count, dtype: int64

In [ ]:
notes.groupby("classe")[matieres].mean().round(1)

        maths  physique  anglais
classe
A         9.8      10.9      9.6
B        10.9      10.8     11.1
C        10.9      12.6      9.4

In [ ]:
notes.nlargest(5, "moyenne")

   etudiant classe  maths  physique  anglais  moyenne mention
15      E16      B     13        18       16     15.7       B
4       E05      A     19        18        9     15.3       B
45      E46      B     15        18       13     15.3       B
6       E07      C     15        11       19     15.0       B
16      E17      B      9        17       18     14.7       B

In [ ]:
notes[(notes["maths"] >= 15) & (notes["anglais"] < 10)]

   etudiant classe  maths  physique  anglais  moyenne   mention
1       E02      B     15        14        0      9.7    Recalé
4       E05      A     19        18        9     15.3         B
17      E18      B     16        18        4     12.7        AB
20      E21      C     16        12        6     11.3  Passable
21      E22      C     19         5        1      8.3    Recalé
24      E25      C     15        17        9     13.7        AB
26      E27      B     18         5        3      8.7    Recalé
33      E34      A     17         4        3      8.0    Recalé
39      E40      A     17        20        5     14.0         B
44      E45      B     20         7        7     11.3  Passable

## 🎉 Bravo !
Prochaines étapes conseillées :
- Refaire le mini-projet sur un **vrai** jeu de données (Kaggle, data.gouv.fr) lu avec `pd.read_csv`
- Apprendre **matplotlib / seaborn** pour les graphiques
- Pratiquer `groupby`, `merge` et les filtres jusqu'à ce que ce soit un réflexe